CREATE TABLE IF NOT EXISTS films
(
    id          int generated by default as identity primary key,
    name        varchar(255) not null,
    releaseDate date         not null,
    description varchar(200) not null,
    duration    int          not null,
    CONSTRAINT check_positive_duration CHECK duration > 0,
    CONSTRAINT not_empty_descr CHECK description != '',
    CONSTRAINT not_empty_name CHECK name != '',
    CONSTRAINT check_release_date_after_1895_12_28 CHECK releaseDate >= PARSEDATETIME('1895-12-28', 'yyyy-MM-dd'),
    CONSTRAINT unique_name_and_release_date UNIQUE(name, releaseDate)
);

CREATE TABLE IF NOT EXISTS users
(
    id         int generated by default as identity primary key,
    login      varchar(100) not null unique,
    name       varchar(100),
    email      varchar(200) not null unique,
    birth_date date         not null,
    CONSTRAINT check_login_not_empty CHECK login NOT LIKE '% %' AND login != '',
    CONSTRAINT check_birth_date_in_past CHECK birth_date < CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id int REFERENCES users (id),
    film_id int REFERENCES films (id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   int REFERENCES users (id),
    friend_id int REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT check_user_and_friend_not_same CHECK friends.user_id != friends.friend_id
);

CREATE TABLE IF NOT EXISTS genre
(
    id   int generated by default as identity primary key,
    name varchar(200) not null,
    CONSTRAINT check_name_not_empty CHECK name != ''
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int REFERENCES films (id),
    genre_id int REFERENCES genre (id),
    PRIMARY KEY (film_id,genre_id)
);

